# @package _global_

algo:
  name: alac
  discount: 0.99
  num_samples: 10
  ema: 0.005
  ld:
    resnet: false
    activation: relu
    ensemble_size: 2
    time_dim: 64
    hidden_dims: [512, 512]
    cond_hidden_dims: [128, 128]
    steps: 20
    step_size: 0.05
    noise_scale: 1.0
    noise_schedule: "none"
    clip_sampler: true
    x_min: -1.0
    x_max: 1.0
    epsilon: 0.001
    lr: 0.0003
    clip_grad_norm: null
