defaults:
  - /config_cfg_def@_here_
  - _self_
  - algo: base # raise error if algo is not specified
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

seed: 0
device: '0'
task: ???
pretrain_only: false
pretrain_steps: 0
train_steps: 1000000
load: null
log:
  dir: logs
  tag: debug
  interval: 500
  save_ckpt: false
  save_video: false
  project: ???
  entity: ???
data:
  dataset: d4rl
  norm_obs: false
  norm_reward: none
  batch_size: 256
  scan: true
  clip_eps: 1e-5
eval:
  interval: 10000
  stats_interval: 2000
  num_episodes: 10
  num_samples: 1
